### ISSUE TITLE
About generate the pkl files?

### ISSUE THREAD

**Issue by hrysj2016** [huang-yh/SelfOcc#12]
Could you please provide the code used for generating the .pkl file for loading the dataset? It would be really helpful for me. Thank you! My email address is [12221089@zju.edu.cn].

**Comment by SeaBird-Go** [comment]
Also want to know how to generate the pkl files. @huang-yh

**Comment by JimPlayboy** [comment]
Great work! 
how can i use these .pkl files for nuscenes mini? if i can't, how can i generate the pkl files?

**Comment by JimPlayboy** [comment]
Great work! 
how can i use these .pkl files for nuscenes mini? if i can't, how can i generate the pkl files?

**Comment by huang-yh** [comment]
We just released the code for sweep synchronization, which is a fundamental step for generating the pkl files we use. 
However, you still need the tokens of keyframe samples to query the nuScenes json tables.

**Comment by jjvanrooy** [comment]
Hi, I want to use the pkl files as well, but it seems there is still not an option to generate the pkl files for the nuscenes mini? Has this issue been solved yet?
